### ISSUE TITLE
Any plan or way to support GPU Rendering?

### ISSUE THREAD

**Issue by ekianjo** [tylermorganwall/rayrender#20]
Hi, very cool project Tyler!
I was wondering if you have any plan to support offloading the rendering to a GPU if available? Would it be possible to use CUDA or OpenCL ?

**Comment by tylermorganwall** [comment]
None anytime in the near future—most GPU-based packages quickly get removed from the CRAN due to compatibility issues, and CUDA is not supported on Windows using the mingw toolchain. 

If R has a significant overhaul in the future that focuses on GPU-computing and improves the ecosystem for packages using GPUs, then I would consider re-hauling the renderer, but it's too much of an undertaking until then.

**Comment by ekianjo** [comment]
Thanks Tyler, I understand.
